font = "/usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf"
font-size = 14
background-color = #1a1b26e6
text-color = #FFFFFF
accent-color = #f5bde6ff
border-width = 2
corner-radius = 8
padding = 16
